### ISSUE TITLE
Fix typo in README

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/corporate_kiss#2]
In the README file, there is a typo in the recommendation for the *CSS Injector* module.

> To customize, it is recommended that you either create the file, css/local.css, in the theme directory and add custom CSS there, or use the css_injecter module.

Please replace the `e` in "css_injecter" by an `o`. (And maybe use the human name *CSS Injector* instead of the machine name).

**Comment by vstemen** [comment]
Fixed.  Thanks for catching that.  I also made some other wording enhancements to the README while I was at it.  Let me know if you spot any other typos.

**Comment by olafgrabienski** [comment]
Thanks for the fix. Reading the README again, I've not found other typos.
